version: "3.0"
#
# Optional: Create volumes to include licence/configuration in the containers.
#
x-vols: &vols
  volumes:
  - ${KX_LICENSE_DIR}:/opt/kx/lic
  - ./cfg:/opt/kx/cfg
  - ./db:/data/db
  - ./cache:/opt/kx/cache
#
# Optional: Create a network for processes to communicate.
#
x-kxnet: &kxnet
  networks:
  - kx

networks:
  kx:
    name: kx
    driver: bridge

#
# Services.
#
services:
  #
  # Resource Coordinator -- 1 per assembly.
  #
  sgrc:
    image: ${KX_DOCKER_REG_DEV}/kxi-sg-rc:${sg_version}
    environment:
      - KXI_NAME=sg_rc
      - KXI_PORT=5060
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:debug # Optional
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${assembly_file_yaml}
      - KXI_AUTH_DISABLED=1
    ports:
      - 127.0.0.1::5060
    stdin_open: true
    tty: true           
    <<: *vols # Optional
    <<: *kxnet # Optional


  #
  # Aggregator. Note we only have one here, but multiple can be configured.
  #
  sgagg:
    image: ${KX_DOCKER_REG_DEV}/kxi-sg-agg:${sg_version}
    environment:
      - KXI_NAME=sg_agg
      - KXI_PORT=5050
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:info # Optional
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${assembly_file_yaml}
      - KXI_SG_RC_ADDR=sgrc:5060
      - KXI_AUTH_DISABLED=1
    ports:
      - 127.0.0.1::5050
    # Optional: deploy multiple replicas.
    deploy:
      mode: replicated
      replicas: 1
    stdin_open: true
    tty: true           
    <<: *vols # Optional
    <<: *kxnet # Optional

  #
  # Gateway.
  #
  sggw:
    image: ${KX_DOCKER_REG_DEV}/kxi-sg-gw:${sg_version}
    environment:
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${assembly_file_yaml}
      - GATEWAY_QIPC_PORT=5040
      - GATEWAY_HTTP_PORT=8080
      - KXI_AUTH_DISABLED=1
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:trace # Optional      
    ports:
      - 127.0.0.1::5040
      - 127.0.0.1::8080
    # Optional: deploy multiple replicas.
    deploy:
      mode: replicated
      replicas: 1
    stdin_open: true
    tty: true     
    <<: *vols # Optional
    <<: *kxnet # Optional

#   sm:
#   #
#   # Storage Manager.
#   #
#     image: ${KX_DOCKER_REG}/kxi-sm:${sm_version}
#     environment:
#       - KXI_NAME=sm
#       - KXI_SC=SM
#       - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${assembly_file_yaml}
#       - KXI_RT_LIB=/opt/kx/cfg/rt_tick_client_lib.q
#       - KXI_PORT=10001
#       - KXI_LOG_FORMAT=text
#       - KXI_LOG_LEVELS=default:trace 
#       - KXI_AUTH_DISABLED=1
#       - KX_TRACE_OBJSTR=1
#       - KX_KURL_DEBUG_LOG=1      
#     env_file:
#       - .env
#       - .cloud_auth_env  
#     ports:
#       - 10001:10001
# ##    stdin_open: false
# ##    tty: false
#     <<: *vols # Optional
#     <<: *kxnet # Optional
  
#   eoi:
  #
  # End of Interval
  #
#     image: ${KX_DOCKER_REG}/kxi-sm-eoi:${sm_version}
#     environment:
#       - KXI_NAME=eoi
#       - KXI_SC=EOI
#       - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${assembly_file_yaml}
#       - KXI_RT_LIB=/opt/kx/cfg/rt_tick_client_lib.q
#       - KXI_PORT=10002
#       - KXI_LOG_FORMAT=text
#       - KXI_LOG_LEVELS=default:trace      
#       - KXI_SM_SMADDR=sm:10001
#       - KXI_AUTH_DISABLED=1  
#       - KX_TRACE_OBJSTR=1
#       - KX_KURL_DEBUG_LOG=1          
#     ports:
#       - 10002:10002
#     env_file:
#       - .env 
#       - .cloud_auth_env      
# ##    stdin_open: false
# ##    tty: false
#     <<: *vols # Optional
#     <<: *kxnet # Optional
  
#   eod:
#   #
#   # End of Day
#   #
#     image: ${KX_DOCKER_REG_DEV}/kxi-sm-eod:${sm_version}
#     environment:
#       - KXI_NAME=eod
#       - KXI_SC=EOD
#       - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${assembly_file_yaml}
#       - KXI_RT_LIB=/opt/kx/cfg/rt_tick_client_lib.q
#       - KXI_PORT=10003
#       - KXI_LOG_FORMAT=text
#       - KXI_LOG_LEVELS=default:trace      
#       - KXI_SM_SMADDR=sm:10001
#       - KXI_SM_EOIADDR=eoi:10002
#       - KXI_AUTH_DISABLED=1      
#       - KX_TRACE_OBJSTR=1
#       - KX_KURL_DEBUG_LOG=1      
#     ports:
#       - 10003:10003
#     env_file:
#       - .env   
#       - .cloud_auth_env          
# ##    stdin_open: false
# ##    tty: false
#     <<: *vols # Optional
#     <<: *kxnet # Optional

#   dbm:
#   #
#   # DBM
#   #
#     image: ${KX_DOCKER_REG_DEV}/kxi-sm-dbm:${sm_version}
#     environment:
#       - KXI_NAME=dbm
#       - KXI_SC=DBM
#       - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${assembly_file_yaml}
#       - KXI_RT_LIB=/opt/kx/cfg/rt_tick_client_lib.q
#       - KXI_PORT=10004
#       - KXI_LOG_FORMAT=text
#       - KXI_LOG_LEVELS=default:trace
#       - KXI_SM_SMADDR=sm:10001
#       - KXI_AUTH_DISABLED=1   
#       - KX_TRACE_OBJSTR=1
#       - KX_KURL_DEBUG_LOG=1             
#     ports:
#       - 10004:10004
#     env_file:
#       - .env   
#       - .cloud_auth_env          
# ##    stdin_open: false
# ##    tty: false
#     <<: *vols # Optional
#     <<: *kxnet # Optional


#   rdb:
#   #
#   # Realtime Database
#   #
#     image: ${KX_DOCKER_REG_DEV}/kxi-da:${da_version}
#     command: -p 5080
#     environment:
#       - KXI_NAME=rdb
#       - KXI_SC=RDB
#       - KXI_LOG_FORMAT=text # Optional
#       - KXI_LOG_LEVELS=default:trace # Optional
#       - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${assembly_file_yaml}
#       - KXI_RT_LIB=/opt/kx/cfg/rt_tick_client_lib.q
#       - KXI_CUSTOM_FILE=/opt/kx/cfg/custom.api.q
#       - KX_TRACE_OBJSTR=1
#       - KX_KURL_DEBUG_LOG=1      
#       - KXI_SG_RC_ADDR=sgrc:5060
#     ports:
#       - 127.0.0.1::5080
#     deploy:
#       mode: replicated
#       replicas: 1
#     env_file:
#       - .env    
#       - .cloud_auth_env         
# ##    stdin_open: false
# ##    tty: false   
#     <<: *vols # Optional
#     <<: *kxnet # Optional



#   idb:
#   #
#   # Intraday Database
#   #
#     image: ${KX_DOCKER_REG_DEV}/kxi-da:${da_version}
#     command: -p 5090
#     environment:
#       - KXI_NAME=idb
#       - KXI_SC=IDB
#       - KXI_LOG_FORMAT=text # Optional
#       - KXI_LOG_LEVELS=default:trace # Optional
#       - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${assembly_file_yaml}
#       - KX_TRACE_OBJSTR=1
#       - KX_KURL_DEBUG_LOG=1    
#       - KXI_CUSTOM_FILE=/opt/kx/cfg/custom.api.q  
#       - KXI_SG_RC_ADDR=sgrc:5060
#       ## - KXI_CUSTOM_FILE=/opt/kx/custom/${custom_idb_code}.q # Optional
#     ports:
#       - 127.0.0.1::5090
#     deploy:
#       mode: replicated
#       replicas: 1
#     env_file:
#       - .env  
#       - .cloud_auth_env           
# ##    stdin_open: false
# ##    tty: false 
#     <<: *vols # Optional
#     <<: *kxnet # Optional


  hdb:
  #
  # Historical Database
  #
    image: ${KX_DOCKER_REG_DEV}/kxi-da:${da_version}
    command: -p 5100 -s 8
    environment:
      - KXI_NAME=hdb
      - KXI_SC=HDB
      - KXI_LOG_FORMAT=text # Optional
      - KXI_LOG_LEVELS=default:trace # Optional
      - KXI_ASSEMBLY_FILE=/opt/kx/cfg/${assembly_file_yaml}
      - KX_TRACE_OBJSTR=1
      - KX_KURL_DEBUG_LOG=1      
      - KX_OBJSTR_CACHE_PATH=/opt/kx/cache
      - KX_S3_CACHE_SIZE=10000
      - KXI_CUSTOM_FILE=/opt/kx/cfg/custom.api.q      
      # - KXI_SG_RC_ADDR=sgrc:5060  ## must be commented out 
    ports:
      - 127.0.0.1::5100
    deploy:
      mode: replicated
      replicas: 2
    env_file:
      - .env 
      - .cloud_auth_env            
##    stdin_open: false
##    tty: false    
    <<: *vols # Optional
    <<: *kxnet # Optional